FROM ppc64le/ubuntu:16.04
MAINTAINER Tom Denham <tom@projectcalico.org>

ADD dist/calicoctl ./calicoctl

ENV CALICO_CTL_CONTAINER=TRUE

# libltdl.so is needed by docker command line tool
# RUN apk add --no-cache libltdl

ENTRYPOINT ["./calicoctl"]
